import { Inter, Aclonica, Convergence } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const aclonica = Aclonica({ subsets: ['latin'], variable: '--font-aclonica', weight: '400' });
const convergence = Convergence({
  subsets: ['latin'],
  variable: '--font-convergence',
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${convergence.variable} ${aclonica.variable} bg-background text-primary antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
