import { Inter, Playfair, Vazirmatn } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const playFair = Playfair({ subsets: ['latin'], variable: '--font-playFair' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${playFair.variable}`}>
      <body>{children}</body>
    </html>
  );
}
